### ISSUE TITLE
In setOnClickListener，setChecked is bad

### ISSUE THREAD

**Issue by softwater** [kyleduo/SwitchButton#12]
First, so sorry my english is very bad.
In my project, I use the SwitchButton, but I meet with a issue. 
I write a test for the issues below.
```java
        sbDefault = (SwitchButton) findViewById(R.id.sb_default);
		sbDefault.setOnClickListener(new View.OnClickListener() {
			@Override public void onClick(View v) {
				sbDefault.setChecked(false);
			}
		});

		final Switch androidSwitch = (Switch) findViewById(R.id.android_switch);
		androidSwitch.setOnClickListener(new View.OnClickListener() {
			@Override public void onClick(View v) {
				androidSwitch.setChecked(false);
			}
		});
```

the 'sdDefault' is the SwitchButton, it doesn't work well, otherwise the 'androidSwitch' is android's Switch widget, it works very good.
I hope you can solve this issue.

**Comment by kyleduo** [comment]
Sorry but this problem is not an issue and I can not figure out why you want to use this widget like this, I mean that will make it useless. But I'm going to tell you why it does not works good.

When you click on the widget, toggle() method was invoked by performClick() method. The Switch widget use the default implementation some like CompoundButton and it is __synchronized__. But SwitchButton from my project override the method with default __asynchronous__ implementation.

For your requirement, you can edit the SwitchButton.java file and change toggle(); method's implementation by calling ___toggle(false);___. The default is ___toggle(true);___

**Comment by Dot01110011** [comment]
This problem is an issue!
