### ISSUE TITLE
setTintColor() makes Thumb get big

### ISSUE THREAD

**Issue by jgutierrez11** [kyleduo/SwitchButton#47]
Hello!

I am testing changing the tint color programmatically with setTintColor but when I run the app, the thumb turns so big that it doesn't looks nice. I don't know why it changes it size. If i set the tint via xml, is working good.

Do I have to set some parameters up in order to setTintColor work properly?
Thanks!

My XML
`
<com.kyleduo.switchbutton.SwitchButton
        android:id="@+id/indicator_switch"
        android:layout_width="match_parent"
        style="@style/SwitchButtonMD"
        app:kswTintColor="@color/teal"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:layout_gravity="right"
        android:gravity="right"/>
`

My Java: 

`login_remember_me.setTintColor(getResources().getColor(R.color.red));
`

Big thumb image

![screen shot 2016-05-09 at 2 09 02 pm](https://cloud.githubusercontent.com/assets/12516663/15124871/b5f1639e-15ef-11e6-9ca2-409929c8d5c2.png)

**Comment by kyleduo** [comment]
Hi, `kswTintColor` and `setTintColor` are used to create geometric style with related color from `tintColor`. Since `SwitchButtonMD` style is complex, `tintColor` is not support it. if you want to create a Material Design style in your own color, **you need to copy resources from `SwitchButtonMD` style and change the colors in them yourself**. I want to keep SwitchButton simple and general so I did not add that much support of Material Design, sorry about that. :)

**Comment by jgutierrez11** [comment]
Ok, I understand. Weird thing is that if I set the tint thru XML it works pretty good, but if I set it thru Java code, it looks weird. Can you please elaborate further in the process of customising the color from copying the resources?

Thanks!

**Comment by kyleduo** [comment]
I've tried your code of xml but no effect and I'm sure that . Which version SwitchButton are you using?

**Comment by jgutierrez11** [comment]
You're right, it doesn't work. Thing is that I use Teal ( a similar color you have in your resources) so I thought it was working. Sorry about that

**Comment by kyleduo** [comment]
It doesn't matter.
