### ISSUE TITLE
setText(.., ...) doesn't call "invalidate()"

### ISSUE THREAD

**Issue by jbir789** [kyleduo/SwitchButton#65]
When setting the text in code, invalidate() isn't called (just requestLayout()), which doesn't redraw the text. I would suggest calling both invalidate() and requestLayout(), as explained here: [Why is requestLayout being called directly after invalidate?](http://stackoverflow.com/a/35281876/3773090)

Also, if I set a text with xml attributes (kswTextOn), the text will be centered. Now, if I update the text in code, the text will keep the position of the initial text and won't look great.

**Comment by kyleduo** [comment]
Hey, these feature works fine on my phone in Demo project. Could you provide your layout to me?

**Comment by julienbiral** [comment]
It works fine in most of the standard scenarios, but in my case, I am adding a countdown to the switch and updating the text (which is the remaining time) with a ```CountdownTimer```. The switch is part of an item in a ```RecyclerView```, and ```requestLayout()``` doesn't make it redraw the view. I could obviously call ```notifyOnDataSetChanged()``` / ```notifyItemChanged(int i)```, but I don't want to do that in this case because it would crash the app if the user was to toggle the switch at the time the view is redrawn, or cause artifacts.

Basically, I want to refresh the text of the ```SwitchButton``` in a ```RecyclerView``` without requesting the View to redraw the item entirely, I would like the switch to update itself and it doesn't work because ```invalidate()``` is not called. I would add that it works fine with a standard ```TextView```, because TextView's ```setText()``` calls ```invalidate()``` after updating the text.

Concerning the second issue (text not centered if different from the initial one) here's a screenshot of what it looks like: I set the initial text o an empty string, and then  updated the text to "0:00 left". You can see that it is not centered anymore, because the text keep the same initial positionas when it was an empty string.

![switchbutton text cutoff](https://cloud.githubusercontent.com/assets/7110330/17709479/13ce746a-639e-11e6-8e22-4d6e8e7cafd8.png)

**Comment by kyleduo** [comment]
I've fixed these problem and pushed to branch [fix_65](https://github.com/kyleduo/SwitchButton/tree/fix_65). Could you please check out that branch and see whether the problem has been solved? Waiting for your reply.

**Comment by julienbiral** [comment]
Everything is good now, thanks for the quick fix!

**Comment by kyleduo** [comment]
I've upload the library and you can use the newest version 1.4.4 with Gradle.

I changed the logic of positioning text and add a new attribute "kswAutoAdjustTextPosition". The new logic will make text looks centered when there are round corners. You can set this attribute to false when at special situation.

**Comment by julienbiral** [comment]
Hey, I thought everything was fine, but I played with a bigger track width and the text is again uncentered. You can reproduce it by, for example, doubling the ```kswBackMeasureRatio```. In my case, the text is again cutoff, as you can see below:

![big track switch](https://cloud.githubusercontent.com/assets/7110330/17786334/36d63ad2-6539-11e6-866c-7eac3e91bb12.png)


I tried playing with ```kswAutoAdjustTextPosition``` but it didn't help either in this case.

**Comment by kyleduo** [comment]
I try to help but I can not reproduce your situation of text not centered. Could you paste your xml? This is what I got when I tried.
![wechatimg1](https://cloud.githubusercontent.com/assets/7019092/17896773/621cb49c-6984-11e6-89b0-7f6c8d87fa76.png)

**Comment by nkukday** [comment]
margins are recomputed only when text does not fit into the size of the current layout but we also need to recompute margins for text when size of the text is smaller than or equal to the size of the current layout to center it properly.

Solved with help and magic from @julienbiral
